name: Build & push to dockerhub
on:
  push:
    branches: ["main"]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
      matrix:
        include:
          - dockerfile: ./Dockerfile-gui
            image: stockbrood/mt5_gui
          - dockerfile: ./Dockerfile-nogui
            image: stockbrood/mt5_nogui

    steps:


