name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "stockbrood"
        password: "Stockbrood"

    - name: Build and Push Image 1
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-gui
        push: true
        tags: |
          stockbrood/mt5_gui:latest
          stockbrood/mt5_gui:${{ github.sha }}

    - name: Build and Push Image 2
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile-nogui
        push: true
        tags: |
          stockbrood/mt5_nogui:latest
          stockbrood/mt5_nogui:${{ github.sha }}
